CREATE TABLE Table1
(
  Id SERIAL PRIMARY KEY,
  A VARCHAR NOT NULL
);

INSERT INTO Table1 (A) VALUES('a');
INSERT INTO Table1 (A) VALUES('b');
INSERT INTO Table1 (A) VALUES('c');
INSERT INTO Table1 (A) VALUES('d');

CREATE TABLE Table2
(
  Id SERIAL PRIMARY KEY,
  B VARCHAR NOT NULL
);

INSERT INTO Table2 (B) VALUES('c');
INSERT INTO Table2 (B) VALUES('d');
INSERT INTO Table2 (B) VALUES('e');

CREATE TABLE Table3
(
  Id SERIAL PRIMARY KEY,
  C VARCHAR NOT NULL
);

INSERT INTO Table3 (C) VALUES('a');
INSERT INTO Table3 (C) VALUES('d');